package app.tripplanner

import android.content.Context
import app.tripplanner.auth.AndroidGoogleSignInProvider
import app.tripplanner.auth.CurrentActivity
import app.tripplanner.shared.platform.GoogleSignInProvider
import org.koin.android.ext.koin.androidContext
import org.koin.dsl.module

/** Android actuals for the platform boundaries in shared/platform (design §6.4). */
fun androidModule() = module {
    single { CurrentActivity() }
    single<GoogleSignInProvider> {
        AndroidGoogleSignInProvider(androidContext(), get(), androidContext().defaultWebClientId())
    }
}

/**
 * `default_web_client_id` is generated by the google-services plugin, which this build applies
 * only when google-services.json exists - so look it up by name instead of via R.
 */
private fun Context.defaultWebClientId(): String {
    val id = resources.getIdentifier("default_web_client_id", "string", packageName)
    return if (id == 0) "" else getString(id)
}
